blank_issues_enabled: false
contact_links:
  - name: Richard Mwewa (Telegram)
    url: https://t.me/rly0nheart/
    about: Please ask and answer questions here.
  - name: Richard Mwewa (Twitter)
    url: https://m.twitter.com/rly0nheart/
    about: Please report security vulnerabilities or bugs here.
